### ISSUE TITLE
SAS-Report does not show up in project list

### ISSUE THREAD

**Issue by CXNQ** [Boemska/create-sas-app#10]
First of all we are very enthusiast about your work you have done, but when we try to retrieve our reports they did not show. Only reports that showed were .sas files

![unknown (1)](https://user-images.githubusercontent.com/48350931/85589251-b5f4ba00-b643-11ea-8ad3-649a095f309f.png)
![unknown (2)](https://user-images.githubusercontent.com/48350931/85589256-b68d5080-b643-11ea-97ef-8f578db65f68.png)
*the text in the images are in dutch*

As you can see in the images above, in Viya it shows 3 reports which 1 is a Sas-Report file and the other 2 are .sas files. But it only shows the .sas files in your app.

How can we fix this?

Secondly how can we show diagrams/graphs in reports like you did in this video: https://vimeo.com/431629954? 

Thank you for reading our question.

**Comment by boemska-nik** [comment]
Hi @CXNQ 


Before I give you the 'long answer', I just want to confirm.

I see you've got the app up and running and talking to your Viya install, that's great.


From your screenshot it looks like you have correctly configured your app with a Folder Root in the Viya, and that location contains two SAS programs and one Visual Analytics report. And when you click the 'open project' button, you see the two SAS programs in the list but not the report.

Is that correct?

**Comment by CXNQ** [comment]
Yes that's correct.

**Comment by boemska-nik** [comment]
Ok, good. Here's the explanation.

The React apps you create with this project are not just a way to render Visual Analytics reports. They are designed to allow you to build custom interfaces and workflows that exchange data with Viya at various steps in your application workflow. 

For example, this allows you to do things like collect that data from a form that the user has filled out in the app, a custom input component or a device sensor, send that data to SAS as a SAS table, process it and return resulting data from SAS and, and then render those results, but using javascript components that you choose, not necessarily VA reports. The vimeo chart you linked to in this issue is an example of that - using a draggable chart component to prepare inputs that are sent to SAS as a SAS table, triggering some SAS code that runs and returns a SAS table, and then rendering that SAS data as a set of 5 charts using a javascript library, in this case [Highcharts](https://github.com/highcharts/highcharts). 

The [project save / load mechanism](https://github.com/Boemska/create-sas-app#secure-saving-loading-and-sharing-of-in-app-projects-viya-only) that you're using to try to load VA reports is not designed to let you load reports directly. What it lets you do is  save a data file which describes the state of your app, most likely in stringified json format - the form selections, results, settings, dashboard layout, anything else you consider to be a 'save file' from your app. You, or other users, can then load these savefiles to load the same project into their app.

CSA also makes it considerably easier for you to implement charting from the SAS Visual Analytics SDK if that is what you are looking to do, but this works slightly differently to what you are assuming.  For example, we've worked on building a portal for a client that, among other things, allowed users to select a set of VA report components and display them in a draggable grid, and customise that portal layout. When they clicked 'save', what was saved to the project file the list of components they chose for their portal, and the layout coordinates for each component. Not the report components themselves.

I suggest you look at using the SAS VA SDK to achieve what you're trying to. It is very well documented - check out the [Getting Started](https://developer.sas.com/sdk/va/docs/getting-started/) link. 

What our project should let you do is play with the SDK without needing to do those first 4 steps: enabling cross-origin resource sharing, cross-site request forgery, enabling cross-site cookies or allowing guest access.  I will open a separate issue to document a step-by-step guide on integrating VA report components into CSA apps, and we may look at publishing our report element selection component as part of that write-up. I'm not sure how soon we'll be able to do that though.

Hope that makes sense.

**Comment by boemska-nik** [comment]
@CXNQ I'm going to close this as I think it answered your question. I've opened #16 to address your use case.
